### ISSUE TITLE
Vignette examples cannot be followed

### ISSUE THREAD

**Issue by mdozmorov** [koustav-pal/HiCBricks#13]
Hi,

I installed HiCBricks as `BiocManager::install("HiCBricks", version = "3.9")` (also, tried the latest version from GitHub). Then, I tried following the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/HiCBricks/inst/doc/IntroductionToHiCBricks.html). The first command:
````
Bintable_path <- system.file(file.path("extdata",
"Bintable_100kb.bins"), package = "HiCBricks")
````
gives empty Bintable_path. 
````
> Bintable_path
[1] ""
````
OK, one can download the file manually from GitHub [Bintable_100kb.bins](https://github.com/koustav-pal/HiCBricks/blob/master/inst/extdata/Bintable_100kb.bins).

The second command also fails:
````
> HiCBricks::Create_many_Bricks(BinTable = Bintable_path, 
...                    bin_delim=" ", output_directory = out_dir, 
...                    file_prefix = "HiCBricks_vignette_test", remove_existing=TRUE, 
...                    experiment_name = "HiCBricks vignette test", resolution = 100000)
Error: 'Create_many_Bricks' is not an exported object from 'namespace:HiCBricks'
````

What may be wrong?

**Comment by koustav-pal** [comment]
Hey @mdozmorov,

Sorry to hear that you are having so much trouble. I think the problem is that you are using the HiCBricks package from Bioconductor release 3.9 with the vignette from release 3.10. Can you please try out these commands? 

First, make sure that you are using R 3.6.0. Next, run

`BiocManager::install("HiCBricks", version = "3.10")`

This should fail because you are still using many dependencies from the previous release. To fix this, run  `BiocManager::install(version="3.10")` to update all packages.

After this is complete, run `BiocManager::install("HiCBricks", version = "3.10")`

**Comment by mdozmorov** [comment]
Thanks, @koustav-pal, that was indeed the problem. Good the README was updated. Will continue playing with the package.
